# Generated by Django 2.1.2 on 2018-11-13 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.IntegerField(null=True)),
                ('to_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='')),
                ('title', models.CharField(max_length=255)),
                ('depth', models.IntegerField(default=-1, null=True)),
                ('html', models.TextField(blank=True, default='')),
                ('review', models.BooleanField(default=False)),
                ('old_rank', models.FloatField(default=0, null=True)),
                ('new_rank', models.FloatField(default=1, null=True)),
                ('content', models.TextField(blank=True, default='')),
                ('sentiment', models.IntegerField(default=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('num_reviews', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='searchterm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='sentiment_analyzer.SearchTerm'),
        ),
        migrations.AddField(
            model_name='link',
            name='searchterm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='sentiment_analyzer.SearchTerm'),
        ),
    ]
